services:
  - type: web
    name: medflapp
    repo: https://github.com/Builderskelechi/MEDFLAPP
    branch: master
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free